name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - master
      - main

jobs:
  build-image-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Frontend Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Frontend Docker Image
      run: |
        docker build -t narwal25/wwa-frontend:${{ github.sha }} .
        docker push narwal25/wwa-frontend:${{ github.sha }}

    - name: Output image tag
      run: echo "IMAGE_TAG=narwal25/wwa-frontend:${{ github.sha }}" >> $GITHUB_ENV
